-- 코드를 작성해주세요
SELECT A.ID, CASE WHEN B.CHILD_COUNT IS NULL THEN 0 ELSE B.CHILD_COUNT END AS CHILD_COUNT
FROM ECOLI_DATA A LEFT JOIN
(
    SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT 
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
) B
ON A.ID = B.PARENT_ID
ORDER BY A.ID