-- 코드를 입력하세요
SELECT A.PRODUCT_CODE, A.PRICE * B.TOTAL_AMOUNT AS SALES
FROM PRODUCT A, 
(SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_AMOUNT
 FROM OFFLINE_SALE
 GROUP BY PRODUCT_ID) B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY 2 DESC, 1 ASC