-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE * (1-B.DISCOUNT_RATE/100) * 30 AS FEE
FROM CAR_RENTAL_COMPANY_CAR A,
CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
WHERE A.CAR_TYPE = B.CAR_TYPE 
AND B.DURATION_TYPE = '30일 이상'
AND A.CAR_TYPE IN ('세단', 'SUV')
AND NOT EXISTS (
    SELECT 1 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    WHERE ((TO_CHAR(C.START_DATE, 'YYYYMMDD') <= '20221101' 
           AND TO_CHAR(C.END_DATE, 'YYYYMMDD') >= '20221101')
           OR(TO_CHAR(C.START_DATE, 'YYYYMMDD') <= '20221130' 
           AND TO_CHAR(C.END_DATE, 'YYYYMMDD') >= '20221130')
           OR(TO_CHAR(C.START_DATE, 'YYYYMMDD') >= '20221101' 
           AND TO_CHAR(C.END_DATE, 'YYYYMMDD') <= '20221130'))
    AND C.CAR_ID = A.CAR_ID
)
AND A.DAILY_FEE * (1-B.DISCOUNT_RATE/100) * 30 >= 500000
AND A.DAILY_FEE * (1-B.DISCOUNT_RATE/100) * 30 < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC