-- 코드를 입력하세요
SELECT YEAR(b.SALES_DATE) as YEAR, MONTH(b.SALES_DATE) AS MONTH, 
a.GENDER, COUNT(DISTINCT(b.USER_ID)) AS USERS FROM USER_INFO a
right outer join ONLINE_SALE b on (a.USER_ID = b.USER_ID)
where a.GENDER is not null
group by YEAR(b.SALES_DATE), MONTH(b.SALES_DATE), a.GENDER
order by YEAR(b.SALES_DATE), MONTH(b.SALES_DATE), a.GENDER