WITH RECURSIVE TEMP AS (
    SELECT 0 AS A
    UNION ALL
    SELECT A+1 FROM TEMP WHERE A<23
)

SELECT A AS HOUR, COUNT(ANIMAL_ID) AS COUNT FROM ANIMAL_OUTS RIGHT OUTER JOIN TEMP 
ON (HOUR(ANIMAL_OUTS.DATETIME)=TEMP.A)
GROUP BY HOUR