WITH RECURSIVE TEMP AS(
    SELECT 0 AS A
    UNION ALL
    SELECT A+1 FROM TEMP WHERE A < 23
)

SELECT D.A HOUR, COUNT(HOUR(C.DATETIME)) COUNT FROM ANIMAL_OUTS C RIGHT OUTER JOIN TEMP D ON (HOUR(C.DATETIME)=D.A)
GROUP BY D.A