-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
SELECT ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RANK, FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO 
)
WHERE RANK = 1
ORDER BY FOOD_TYPE DESC