-- 코드를 작성해주세요
SELECT A.ID 
     , CASE WHEN A.RANK <= B.CNT / 4 * 1 THEN 'CRITICAL'
            WHEN A.RANK <= B.CNT / 4 * 2 THEN 'HIGH'
            WHEN A.RANK <= B.CNT / 4 * 3 THEN 'MEDIUM'
            ELSE 'LOW' END AS "COLONY_NAME"
FROM (
select ID, ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) AS "RANK", SIZE_OF_COLONY
from ECOLI_DATA 
) A,
(SELECT COUNT(ID) AS "CNT" FROM ECOLI_DATA
) B
ORDER BY A.ID