-- 코드를 입력하세요
SELECT C.APNT_NO, A.PT_NAME, A.PT_NO, C.MCDP_CD, B.DR_NAME, C.APNT_YMD
FROM PATIENT A, DOCTOR B, APPOINTMENT C
WHERE A.PT_NO = C.PT_NO
AND B.DR_ID = C.MDDR_ID
AND TO_CHAR(C.APNT_YMD, 'YYYYMMDD') = '20220413'
AND C.APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD