-- 코드를 작성해주세요
SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO C, ITEM_TREE D
WHERE C.ITEM_ID = D.ITEM_ID
AND D.PARENT_ITEM_ID IN
(
SELECT B.PARENT_ITEM_ID FROM ITEM_INFO A, ITEM_TREE B
WHERE A.ITEM_ID = B.PARENT_ITEM_ID
AND A.RARITY = 'RARE'
AND B.PARENT_ITEM_ID IS NOT NULL
)
ORDER BY C.ITEM_ID DESC