-- 코드를 입력하세요
SELECT EXTRACT(MONTH FROM A.START_DATE) AS MONTH, A.CAR_ID, COUNT(A.CAR_ID) AS RECORDS 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A,
(
    SELECT CAR_ID, COUNT(CAR_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
) B
WHERE A.CAR_ID = B.CAR_ID
AND TO_CHAR(A.START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
GROUP BY EXTRACT(MONTH FROM A.START_DATE), A.CAR_ID
ORDER BY 1 ASC, 2 DESC