-- 코드를 작성해주세요
SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, B.MAX_SIZE_OF_COLONY - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM ECOLI_DATA A
,(SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
FROM ECOLI_DATA 
GROUP BY YEAR(DIFFERENTIATION_DATE)) B
WHERE YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY 1 ASC, 2 ASC