-- 코드를 작성해주세요
SELECT B.ID, A.FISH_NAME, B.LENGTH FROM FISH_NAME_INFO A, 
(SELECT ID, FISH_TYPE, LENGTH
      , RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS "RANK"
 FROM FISH_INFO
 WHERE LENGTH > 10
    )B
WHERE A.FISH_TYPE = B.FISH_TYPE
AND B.RANK = '1'
ORDER BY ID