-- 코드를 작성해주세요
SELECT D.SCORE, D.EMP_NO, D.EMP_NAME, D.POSITION, D.EMAIL FROM
(
select C.SCORE, C.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL, 
    DENSE_RANK() OVER(ORDER BY C.SCORE DESC) AS "RANK"
from HR_EMPLOYEES B, 
(SELECT EMP_NO, SUM(SCORE) AS SCORE FROM HR_GRADE
 WHERE YEAR = '2022'
 GROUP BY EMP_NO
) C
where B.EMP_NO = C.EMP_NO 
) D
WHERE D.RANK = 1