-- 코드를 입력하세요
SELECT A.CATEGORY, A.PRICE AS MAX_PRICE, A.PRODUCT_NAME FROM 
 FOOD_PRODUCT A
 ,(SELECT MAX(PRICE) AS PRICE, CATEGORY from FOOD_PRODUCT 
    group by CATEGORY) B
WHERE A.PRICE = B.PRICE
AND A.CATEGORY = B.CATEGORY
AND A.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY 2 DESC