-- 코드를 작성해주세요
SELECT CASE WHEN GROUP_CONCAT(B.CATEGORY) LIKE '%Front End%'
             AND GROUP_CONCAT(B.NAME) LIKE '%Python%' THEN 'A'
            WHEN GROUP_CONCAT(B.NAME) LIKE '%C#%' THEN 'B'
            WHEN GROUP_CONCAT(B.CATEGORY) LIKE '%Front End%' THEN 'C' 
            END AS GRADE
     , A.ID
     , A.EMAIL
FROM DEVELOPERS A, SKILLCODES B
WHERE A.SKILL_CODE & B.CODE = B.CODE
GROUP BY A.ID, A.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY 1, 2